# Generated by Django 4.1.6 on 2023-02-12 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role', models.CharField(default='', max_length=30)),
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(default='', max_length=30)),
                ('phone', models.IntegerField(default=0)),
                ('online_or_offline', models.CharField(default='', max_length=30)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(default='', max_length=30)),
                ('major', models.CharField(default='', max_length=30)),
                ('grade', models.CharField(default='', max_length=30)),
                ('institute', models.CharField(default='', max_length=30)),
                ('school', models.CharField(default='', max_length=30)),
                ('online_or_offline', models.CharField(default='', max_length=30)),
                ('student_phone', models.CharField(default='', max_length=30)),
                ('mother_phone', models.CharField(default='', max_length=30)),
                ('father_phone', models.CharField(default='', max_length=30)),
                ('home_phone', models.CharField(default='', max_length=30)),
                ('support_name', models.CharField(default='', max_length=30)),
                ('counselor_name', models.CharField(default='', max_length=30)),
                ('manager_name', models.CharField(default='', max_length=30)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
