# Generated by Django 4.1.6 on 2023-04-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permission',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
