# Generated by Django 4.1.6 on 2023-02-13 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='counselor_name',
            new_name='counselor_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='manager_name',
            new_name='manager_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='support_name',
            new_name='support_id',
        ),
    ]
