# Generated by Django 4.1.6 on 2023-02-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_sumofstudy'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permission',
            field=models.JSONField(default=dict),
        ),
    ]
