# Generated by Django 4.1.6 on 2023-04-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_student_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='institute',
            field=models.CharField(default='', max_length=30),
        ),
    ]
