# Generated by Django 4.1.6 on 2023-02-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sms',
            field=models.BooleanField(default=False),
        ),
    ]
