# Generated by Django 4.1.6 on 2023-02-23 14:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_name', models.CharField(default='', max_length=40)),
                ('tutorial_type', models.IntegerField(default=0)),
                ('tutorial_price', models.IntegerField(default=0)),
                ('tutorial_discount', models.IntegerField(default=0)),
                ('tutorial_image', models.ImageField(blank=True, upload_to='tutorial_images')),
                ('tutorial_content', models.TextField(default='')),
                ('tutorial_file', models.FileField(blank=True, upload_to='tutorial_files')),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tutorial_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
