# Generated by Django 4.1.6 on 2023-02-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_payment_payment_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_data',
            field=models.JSONField(default=dict),
        ),
    ]
