# Generated by Django 4.1.6 on 2023-02-14 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_rename_craeted_at_payment_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
